apiVersion: apps/v1   
kind: Deployment      
metadata:
  name: app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          